export default function DataMethodology() {
  return <section className="sources" aria-labelledby="sources-title"><p className="eyebrow">UNDERSTAND THE CONTEXT</p><h2 id="sources-title">Data & Methodology</h2><div className="source-grid">
    <div><h3>Census of India</h3><p>Primary Census Abstract · Reference year: 2011</p><p>Historical total, rural and urban population context, not a current population estimate.</p></div>
    <div><h3>Jal Jeevan Mission</h3><p>Reported rural household tap-connection coverage</p><strong>Snapshot: 21 September 2026</strong><p>J1/J5 reconciled coverage includes households without PWS in its denominator. Reported connections do not independently verify service functionality.</p></div>
    <div><h3>Citizen demand</h3><p>Baseline requests are synthetic demo data. New user submissions may also be present; individual records are not labelled by origin. Counts include all categories and area types; percentages use all requests as denominator. Rounding can prevent totals of exactly 100%. Reported citizen requests do not represent the Karnataka population or official district performance.</p></div>
    <div><h3>Rural water scoring</h3><p>Only RURAL + WATER requests contribute. Requests per 100k = rural WATER count / Census rural population × 100,000. Demand index = (district rate − minimum rate) / (maximum rate − minimum rate) × 100; equal rates yield zero.</p><p>Infrastructure gap = 100 − JJM coverage. Priority score = demand index × 0.5 + infrastructure gap × 0.5. LOW: below 25; MEDIUM: 25–49.99; HIGH: 50–74.99; VERY_HIGH: 75–100. Missing data remains incomplete, not estimated.</p></div>
    <div><h3>Planning profiles</h3><p>Deterministic evidence rules consider demand and infrastructure gaps to suggest prototype planning considerations. They do not call Gemini and are not official government recommendations. The Rural Water view shows the selected profile, evidence and limitations.</p></div>
    <div><h3>AI interpretation and voice</h3><p>Gemini interprets citizen text; users should review the preview before submitting. The stored classification may differ from the preview. Gemini does not calculate priority scores.</p><p>Google Cloud Speech-to-Text transcribes English, Kannada and Hindi voice input. Review and edit transcription before analysis; transcription alone does not submit a request.</p></div>
    <div><h3>District reference map</h3><p>Google Maps markers represent verified district headquarters/reference locations, not complaint locations, infrastructure project locations or exact district centroids. Reference coordinates are attributed to OpenStreetMap contributors. Ramanagara uses the historical dataset name; its administrative naming context appears in the selected map reference.</p></div>
  </div><div className="notice"><strong>Priority scores are prototype relative indicators for demonstration. They are not official government rankings or policy recommendations.</strong><p>Demand is normalized relative to the districts currently analysed. Adding citizen requests to one district can therefore change normalized demand scores for other districts.</p></div></section>;
}
